### ISSUE TITLE
[Bug]: False positive

### ISSUE THREAD

**Issue by Robert-M-Muench** [ParetoSecurity/pareto-mac#136]
### What happened?

<img width="930" alt="image" src="https://user-images.githubusercontent.com/1826391/230429872-8cc4ab8e-7fd9-40c8-87e0-4b8a054c125e.png">

### Version

Latest

**Comment by dmurko** [comment]
Click "Run Checks" - it's been one year since the last check. Which is another thing we should look into. :)

**Comment by Robert-M-Muench** [comment]
🫤🙄🫢 ... yes, like re-running it automatically on start. That's what I expected.

**Comment by dfjs** [comment]
I've also just had a false positive, despite the last check being run minutes before (rather than a year!). Re-running resolved it, but is there something more to this?

e.g. I noticed that there was an update due 

<img width="185" alt="image" src="https://user-images.githubusercontent.com/1366169/232555174-9049b5dc-2e03-48d3-8682-1d1e3846a707.png">

Let me know if there's any additional info I can share 🙏

**Comment by dz0ny** [comment]
@dfjs  Do you have the app running in the background?

About the update Setapp has a strict rule that it won't update an app once you decline the app or Setapp update. From that point on you have to manually trigger the update from the Setapp by checking for Setapp updates.

**Comment by dfjs** [comment]
thanks for getting back to me @dz0ny, and yes I have it running in the background.

I don't believe I've declined app updates (Setapp Settings > Updates > Install automatically is checked, and is successfully checking for updates). Would that have a bearing on the false positives?

**Comment by dz0ny** [comment]
> thanks for getting back to me @dz0ny, and yes I have it running in the background.
> 
> I don't believe I've declined app updates (Setapp Settings > Updates > Install automatically is checked, and is successfully checking for updates). Would that have a bearing on the false positives?

What happens if you click on "Check for updates..."
<img width="738" alt="image" src="https://user-images.githubusercontent.com/239513/232566945-73d6ad34-28fc-4692-bc66-1ec0e3fb43b7.png">

This is from their docs https://docs.setapp.com/docs/faq#can-somebody-setapp-or-i-force-users-to-update-setapp-and-consequently-setapp-apps

**Comment by dfjs** [comment]
@dz0ny yes that triggers the Setapp update flow, I ran this after you got back to me the first time and am updated now. Do you think this should have a bearing on the false positive?

**Comment by dz0ny** [comment]
> @dz0ny yes that triggers the Setapp update flow, I ran this after you got back to me the first time and am updated now. Do you think this should have a bearing on the false positive?

No, since the background operation should happen at least once a day. Can you email the output of [paretosecurity://logs](paretosecurity://logs) to support@paretosecuritry.com?

**Comment by dz0ny** [comment]
There are a couple of exceptions where macOS would not run the background job, as we use it to schedule the scanning process, however from the logs I don't see the case yet. I will close this issue and reopen it if we get another report.
