### ISSUE TITLE
[Bug]: Firewall reported as off when terminal and system settings disagree

### ISSUE THREAD

**Issue by ColoursofOSINT** [ParetoSecurity/pareto-mac#139]
### What happened?

Thank you for the software. Pareto is showing a warning that stealth mode on my mac is off, even though system settings displays it as on. 

As per #135, I understand that system settings may be misleading, so I ran and received: 

`/usr/libexec/ApplicationFirewall/socketfilterfw --getglobalstate --getblockall --getallowsigned --getstealthmode

Firewall is enabled. (State = 1)
Block all DISABLED!
Automatically allow signed built-in software ENABLED
Automatically allow downloaded signed software ENABLED
ALF: Error, kStealthEnableKey does not return the correct type.`

With the weird error I attempted to force the stealth mode on with:

`sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setstealthmode on

Stealth mode enabled`

It appeared to work, but Pareto did not change its errors so I ran: 

`/usr/libexec/ApplicationFirewall/socketfilterfw --getstealthmode

ALF: Error, kStealthEnableKey does not return the correct type.`

Any tips on resolving this. I do have a firewall (Little Snitch), so perhaps that's the issue.

### Version

1.7.68 - 5278

**Comment by ColoursofOSINT** [comment]
Also, running:

`sudo defaults read /Library/Preferences/com.apple.alf.plist stealthenabled' 

Returns a 1 (enabled).

**Comment by dz0ny** [comment]
It mostly means that Firewall itself cannot read the configuration file. I believe this occurs because of transfer/backup as other apps cannot modify this file. You can try removing the file with `rm /Library/Preferences/com.apple.alf.plist` and then setting the firewall again. 

Regarding using the **defaults**:

`sudo defaults read /Library/Preferences/com.apple.alf.plist stealthenabled' is not a real indication of what the actual applied setting is since it only reads file. The socketfilterfw reads the actual state of firewall, and in your case it cannot properly parse even the internal state.

Hopefully, this clarifies what the issue is.

**Comment by ColoursofOSINT** [comment]
I tried to both send the file to the trash, and also

`
rm /Library/Preferences/com.apple.alf.plist
`

After resetting the firewall, I get the same error. Any more tips?

**Comment by dz0ny** [comment]
Try ```sudo rm /Library/Preferences/com.apple.alf.plist``` then ```sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setstealthmode on```, reboot so that changes sync and they you should be good to go.
