### ISSUE TITLE
Does not consider screen turning off before the screensaver would kick in

### ISSUE THREAD

**Issue by Rotonen** [ParetoSecurity/pareto-mac#62]
### What happened?

I have my screen turning off at 5 minutes, resulting in the device being locked, and the screensaver would kick in at whatever the default is (20 minutes?). Pareto currently flags my setup as insecure due to this, even though the target of locking the screen within 5 minutes of interactivity is achieved.

### Version

HW: MacBookPro11,3
macOS: Version 11.6 (Build 20G165)
App Version: 1.2.9
Build: 2438

**Comment by zupo** [comment]
Mhm, makes sense, thanks for the report!

**Comment by dz0ny** [comment]
Resolved in https://github.com/teamniteo/pareto/issues/257

The issue is complex, Apple moved a lot of settings to MobileKeyBag (you can think of is a keychain with conditional iCloud sync) inherited from iOS. The fallback method that was used before this version https://github.com/ParetoSecurity/pareto-mac/releases/tag/1.6.52 was using an old interface that is no longer reporting correct values.

**Comment by zupo** [comment]
Related commit: https://github.com/ParetoSecurity/pareto-mac/commit/e13d3f03d09871f4e8fb47ef26d13c447f0ad188
